import { Geist, Geist_Mono, Poppins, Zen_Dots, Inter, Syne, JetBrains_Mono } from "next/font/google";
import "./globals.scss";
import { ThemeProvider } from "@/context/ThemeContext";
import ThemeFAB from "@/components/ThemeFAB";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins-family",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const zenDots = Zen_Dots({
  variable: "--font-zen-dots",
  subsets: ["latin"],
  weight: ["400"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const syne = Syne({
  variable: "--font-syne",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsmono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const c_id = ["w73b", "s146", "63"].join("");
w73bs14663

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${zenDots.variable} ${inter.variable} ${syne.variable} ${jetBrainsMono.variable} h-full antialiased`}
    >
      <body className="h-screen font-syne bg-[var(--surface-0)]">
        <Script id="ms-clarity" strategy="afterInteractive">
          {`
            (function(c,l,a,r,i,t,y){
              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "${c_id}");
          `}
        </Script>

        <main className="h-full bg-[var(--surface-0)]">
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </main>
      </body>
    </html >
  );
}
